import './global.css';

import NavProgressBar from '@vctqs1/nav-progress-bar-react';
import Link from 'next/link';

export const metadata = {
  title: 'Welcome to nextjs-app-router',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavProgressBar primary='#3fffa8' />
        <header className="app-nav">
          <nav aria-label="Primary" className="app-nav-inner">
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/products/1">Product 1</Link>
            <Link href="/products/2">Product 2</Link>
            <Link href="/products/3">Product 3</Link>
          </nav>
        </header>
        <main className="app-shell">{children}</main>
      </body>
    </html>
  );
}
